### ISSUE TITLE
Get Current Location of the user and display them on the map

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#11] opened 2020-03-03 19:02 UTC

**Comment by infiniteoverflow** [comment] 2020-03-03 19:34
I would like to work on this

**Comment by vineetjk** [comment] 2020-03-04 04:15
I would like to work on this

**Comment by myselfanuj** [comment] 2020-03-04 04:49
I would like to work on it I already made an project using google map API and have experience of working on API. Please assign me this issue

**Comment by ankitshaw** [comment] 2020-03-04 05:27
@myselfanuj issue assigned to you. 
@vineetjk you have already been assigned an issue.
@infiniteoverflow please give us some time to verify you PR. We are assigning one issue per participant till the PR for the issue is accepted. Thank You for your patience.

**Comment by neversettle17-101** [comment] 2020-03-14 14:29
If the issue is still open I would like to work on it

**Comment by myselfanuj** [comment] 2020-03-14 16:00
I am working on it.

**Comment by kichloo** [comment] 2020-03-20 14:46
@ankitshaw I can work on this issue.

**Comment by myselfanuj** [comment] 2020-03-20 15:03
I am already working on it and my work is about to finish but this issue is unassigned by mistake please assigned me this issue again so other people didn't comment here.@ankitshaw

**Comment by Abbeyme1** [comment] 2020-03-22 07:25
@ankitshaw I would like to work on this.

**Comment by myselfanuj** [comment] 2020-04-05 13:51
Sorry, I can't work on this right now you can assign it to others who are willing to work... sorry for late response..

**Comment by 991rajat** [comment] 2020-04-08 15:46
Hello, I would like to contribute.

**Comment by sanxy** [comment] 2020-04-14 00:08
If this becomes open I will like to work on this

**Comment by tanmayrauth** [comment] 2020-04-18 04:51
@991rajat Any update on this? Please do let us know otherwise need to assign it it someone else

**Comment by kichloo** [comment] 2020-04-18 05:10
@ankitshaw I had first asked to work on it. How can the person who asks last be assigned instead of someone who asked first. I thought FCFS is followed. Didn't know this project follows something else

**Comment by tanmayrauth** [comment] 2020-04-18 06:10
@kichloo you can see there are many request raised for it. Even after assigning them they don't actively contribute or atleast provide the update for blocker.
If @991rajat fails to respond back with update in next 1 day then you can pick up this issue if you are interested

**Comment by ankitshaw** [comment] 2020-04-18 12:06
> @ankitshaw I had first asked to work on it. How can the person who asks last be assigned instead of someone who asked first. I thought FCFS is followed. Didn't know this project follows something else

Hi @kichloo , please keep a track on the gssoc slack space as well, I had asked participants to comment on issue, if they find stale or inactive issues (on 11th April). That was done to identify who really want to take up issues and not just block it.

**Comment by ankitshaw** [comment] 2020-04-19 18:41
Hi @kichloo, I have assigned you the issue.

**Comment by tanmayrauth** [comment] 2020-04-26 11:46
@kichloo are you working on this issue?

**Comment by kichloo** [comment] 2020-04-29 06:38
I have raised a PR. Pl look at it.

**Comment by bharatmk2567** [comment] 2020-04-29 14:16
I don't see location on my screen
Can you share some screenshots?

**Comment by kichloo** [comment] 2020-04-29 15:27
API key is required for it, did you do it? And I am a beginner, I have not tested it.

**Comment by ankitshaw** [comment] 2020-05-02 15:08
current location share feature is already working so key already added to the repo

**Comment by kichloo** [comment] 2020-05-02 15:31
@ankitshaw So is it over that means I have to do anything more in it?

**Comment by kichloo** [comment] 2020-05-02 17:36
Ok, I will make a new PR.

**Comment by ankitshaw** [comment] 2020-05-02 18:35
I have closed your PR refer the comment added there

**Closed as completed** 2020-05-03 17:04 UTC
Labels: enhancement, help wanted, wontfix, medium, gssoc20
